'use strict';

const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  // Путь брошенного в окно файла: у File в renderer свойства path больше нет.
  pathForFile: (file) => webUtils.getPathForFile(file),
  openDialog: () => ipcRenderer.invoke('open-dialog'),
  addTorrent: (source, savePath) => ipcRenderer.invoke('add-torrent', source, savePath),
  defaultDownloadPath: () => ipcRenderer.invoke('default-download-path'),
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  prepare: (index) => ipcRenderer.invoke('prepare', index),
  playUrl: (index, seekSec, audioTrack) => ipcRenderer.invoke('play-url', index, seekSec, audioTrack),
  subsUrl: (index, track, fromSec) => ipcRenderer.invoke('subs-url', index, track, fromSec),
  setWindowButtons: (visible) => ipcRenderer.invoke('set-window-buttons', visible),
  setLanguage: (lang) => ipcRenderer.invoke('set-language', lang),
  fitAspect: (w, h) => ipcRenderer.invoke('fit-aspect', w, h),
  clearAspect: () => ipcRenderer.invoke('clear-aspect'),
  showInFolder: (p) => ipcRenderer.invoke('show-in-folder', p),
  cacheSubtitles: (index, track) => ipcRenderer.invoke('cache-subtitles', index, track),
  chooseSubtitle: () => ipcRenderer.invoke('choose-subtitle'),
  externalSubs: (filePath) => ipcRenderer.invoke('external-subs', filePath),
  searchSubtitles: (apiKey, query) => ipcRenderer.invoke('search-subtitles', apiKey, query),
  downloadSubtitle: (apiKey, fileId) => ipcRenderer.invoke('download-subtitle', apiKey, fileId),
  prefetch: (index, bytes) => ipcRenderer.invoke('prefetch', index, bytes),
  fileProgress: (index) => ipcRenderer.invoke('file-progress', index),
  torrentStats: () => ipcRenderer.invoke('torrent-stats'),
  toggleFullscreen: () => ipcRenderer.invoke('toggle-fullscreen'),
  exitFullscreen: () => ipcRenderer.invoke('exit-fullscreen'),
  onOpenSettings: (cb) => ipcRenderer.on('open-settings', () => cb()),
  onOpenShortcuts: (cb) => ipcRenderer.on('open-shortcuts', () => cb()),
  onOpenAbout: (cb) => ipcRenderer.on('open-about', () => cb()),
  appVersion: () => ipcRenderer.invoke('app-version'),
  onOpenDialog: (cb) => ipcRenderer.on('open-dialog-request', () => cb()),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  saveFile: (index) => ipcRenderer.invoke('save-file', index),
  setAlwaysOnTop: (on) => ipcRenderer.invoke('set-always-on-top', on),
  setAllDesktops: (on) => ipcRenderer.invoke('set-all-desktops', on),
  getRememberWindow: () => ipcRenderer.invoke('get-remember-window'),
  setRememberWindow: (on) => ipcRenderer.invoke('set-remember-window', on),
  isDefaultHandler: () => ipcRenderer.invoke('is-default-handler'),
  makeDefaultHandler: () => ipcRenderer.invoke('make-default-handler'),
  removeDefaultHandler: () => ipcRenderer.invoke('remove-default-handler'),
  onFullscreen: (cb) => ipcRenderer.on('fullscreen', (_e, v) => cb(v)),
  onOpenSource: (cb) => ipcRenderer.on('open-source', (_e, src) => cb(src)),
});
